### ISSUE TITLE
Would you accept a PR that sends remaining measurements when the application is stopping?

### ISSUE THREAD

**Issue by devstopfix** [bmuller/telemetry_metrics_cloudwatch#8]
Hi @bmuller thanks for this library!

We are using it in AWS Batch, and it's possible that there are unsent metrics when the application gracefully stops. 
Would you be open to a PR that sends any unsent measurements in the terminate callback of the genserver?

Alternatively a `flush()` call which would also send all cached measurements. Otherwise we may have to introduce a sleep to ensure this library has time to send and pending data.

**Comment by bmuller** [comment]
Hey @devstopfix - sure, I'd be happy to take a look at a PR that handles syncing on `terminate`.

**Comment by devstopfix** [comment]
Thanks! I will test it today and if it works will share it - it's tiny!

**Comment by devstopfix** [comment]
Raised a PR #9 - I think this is enough. 
At least it gives an opportunity to send a stop message to the telemetry process

**Comment by bmuller** [comment]
Closing w/ #9 merge
